In [1]:
import MySQLdb.connections
import pandas as pd
import re
from collections import defaultdict

In [2]:
#!/usr/bin/python
# -*- coding: <UTF-8> -*-

# MySQL Configuration 
#
config = {
            'user': '',
            'password': '',
            'host': '',
            'database': ''
		}

In [3]:
con = MySQLdb.connections.Connection(host = '127.0.0.1', user = 'root', passwd = 'zsj0406',db = 'test' )

In [4]:
c = con.cursor()

In [5]:
c.execute('select * from Messages')

44247

In [6]:
data = c.fetchall()

In [8]:
import numpy as np

In [9]:
data_test = np.array(data)

In [10]:
df = pd.DataFrame(data_test)

In [11]:
df.columns = ['Msg_ID', 'Usr_ID', 'Conv_ID', 'Rel_ID', 'Gender', 'Message', 'Date', 'Time', 'Send']

In [12]:
df

Msg_ID Usr_ID Conv_ID  Rel_ID Gender  \
0      M00001    U01    C000    mass    unk   
1      M00002    U01    C171     unk    unk   
2      M00003    U01    C171     unk    unk   
3      M00004    U01    C171     unk    unk   
4      M00005    U01    C171     unk    unk   
5      M00006    U01    C171     unk    unk   
6      M00007    U01    C171     unk    unk   
7      M00008    U01    C171     unk    unk   
8      M00009    U01    C000    mass    unk   
9      M00010    U01    C026     rel      f   
10     M00011    U01    C026     rel      f   
11     M00012    U01    C026     rel      f   
12     M00013    U01    C999     unk    unk   
13     M00014    U01    C000    mass    unk   
14     M00015    U01    C000    mass    unk   
15     M00016    U01    C000    mass    unk   
16     M00017    U01    C027  friend    unk   
17     M00018    U01    C027  friend    unk   
18     M00019    U01    C027  friend    unk   
19     M00020    U01    C027  friend    unk   
20     M00021    U01    C000    mass    unk   
21     M00022    U01    C000    mass    unk   
22     M00023    U01    C028     unk    unk   
23     M00024    U01    C028     unk    unk   
24     M00025    U01    C028     unk    unk   
25     M00026    U01    C000    mass    unk   
26     M00027    U01    C029     unk    unk   
27     M00028    U01    C029     unk    unk   
28     M00029    U01    C029     unk    unk   
29     M00030    U01    C172     unk    unk   
...       ...    ...     ...     ...    ...   
44217  M44225    U15    C164  casual      f   
44218  M44226    U15    C164  casual      f   
44219  M44227    U15    C164  casual      f   
44220  M44228    U15    C164  casual      f   
44221  M44229    U15    C164  casual      f   
44222  M44230    U15    C164  casual      f   
44223  M44231    U15    C164  casual      f   
44224  M44232    U15    C164  casual      f   
44225  M44233    U15    C165  casual      f   
44226  M44234    U15    C165  casual      f   
44227  M44235    U15    C165  casual      f   
44228  M44236    U15    C165  casual      f   
44229  M44237    U15    C165  casual      f   
44230  M44238    U15    C165  casual      f   
44231  M44239    U15    C165  casual      f   
44232  M44240    U15    C165  casual      f   
44233  M44241    U15    C165  casual      f   
44234  M44242    U15    C165  casual      f   
44235  M44243    U15    C165  casual      f   
44236  M44244    U15    C140     unk      f   
44237  M44245    U15    C140     unk    unk   
44238  M44246    U15    C143     unk    unk   
44239  M44247    U15    C147     unk    unk   
44240  M44248    U15    C147     unk    unk   
44241  M44249    U15    C147     unk    unk   
44242  M44250    U15    C147     unk    unk   
44243  M44251    U15    C151     unk    unk   
44244  M44252    U15    C151     unk    unk   
44245  M44253    U15    C162     unk    unk   
44246  M44254    U15    C162     unk    unk   

                                                 Message                 Date  \
0        [NAME, 6]  [Notice] Scholarship Available, o...  0015-05-14 00:00:00   
1                           Say thank you if you got it.  0015-05-13 00:00:00   
2                                     I have not got it.  0015-05-13 00:00:00   
3      Thank you i got it. Sometimes my celphone does...  0015-05-13 00:00:00   
4                                          Dejame saber.  0015-05-13 00:00:00   
5                   Ahora ya lo recibi muchas gracias :)  0015-05-13 00:00:00   
6      Se–or [NAME, 6] ayer le mande.un.mensaje que s...  0015-05-14 00:00:00   
7                                  Yo recibi tu mensaje.  0015-05-14 00:00:00   
8                                        Bienvenido[WEB]  0015-05-12 00:00:00   
9      Tia Feliz dia de las madres la quiero un monto...  0015-05-10 00:00:00   
10     Gracias hija por sus buenos deseos la quiero m...  0015-05-10 00:00:00   
11     Gracias hija por sus buenos deseos la quiero m...  0015-05-10 00:00:00   
12         [Name, 10] mil disculpa me.o

In [13]:
emo = pd.read_csv('./Emoji_Codes.csv')
emo_a = pd.np.array(emo)

In [14]:
emo_dict = {('[EMO, %d]' % item[1]): item for item in emo_a}

In [15]:
p = re.compile('\[EMO, \d+\]')

In [16]:
counts = defaultdict(int)

In [17]:
for text in  df['Message']:
	matches = re.findall(p, text)
	if matches:
		for match in matches:
			if match in emo_dict:
				matched_emo = emo_dict[match][0]
				counts[matched_emo] += 1

In [18]:
sorted_counts = sorted(counts.items(), key=lambda x: x[1])

In [19]:
sorted_counts.reverse()

In [20]:
sorted_counts[0:5]

[('😘', 4855), ('😂', 2056), ('😍', 1799), ('😃', 1048), ('😳', 948)]

By checking the table of Emoji, the Emoji Order: [EMO,8],[EMO,23],[EMO,7],[EMO,2],[EMO,15]

In [65]:
def transfer(x):
    Temp_list = []
    for item in df['Message']:
        if ('[EMO, %d]' %x) in item:
            Temp_list.append(item)
    Temp_list = [re.sub(p, '', item) for item in Temp_list]
    Temp_list = np.array([x for x in Temp_list if x != ''])
    Temp_df = pd.DataFrame(Temp_list)
    Temp_df.columns = ['text']
    a = np.empty(len(Temp_list))
    a.fill(x)
    Temp_df['Label'] = a
    return(Temp_df)

In [54]:
Data = pd.DataFrame(columns=['text','Label'])

In [67]:
Data = Data.append(transfer(8), ignore_index = True)

In [69]:
Data = Data.append(transfer(23), ignore_index = True)

In [70]:
Data = Data.append(transfer(7), ignore_index = True)

In [71]:
Data = Data.append(transfer(2), ignore_index = True)

In [72]:
Data = Data.append(transfer(15), ignore_index = True)

In [73]:
Data

text  Label
0                                  P E R D O N A N D O     8.0
1     exageran eres un hermoso bomboncito de chocolate     8.0
2                                       Gracias Bella è    8.0
3                                   I wanna be with you    8.0
4                                         Sweet dreams     8.0
5     So tomorrow is another day.  I see you tomorro...    8.0
6     Good night  I'll hit you up and see how work w...    8.0
7                                      Good night  ttut    8.0
8     I hope not! I'm in the train now so I'll ttyl....    8.0
9                                           Good night     8.0
10                                          Thanks! Gn     8.0
11                                               Nightè    8.0
12                                                 Aww     8.0
13                                           Sleep well    8.0
14                                         Good night      8.0
15                                          Good Night     8.0
16                                          Good night     8.0
17                                          Good night     8.0
18                                 Good night beautiful    8.0
19                                  Lol okay goodnight     8.0
20    Thanks for telling me you didn't like me. Good...    8.0
21                                          Good night     8.0
22                                        Good morning     8.0
23                                       Good morning!!    8.0
24         Alright have a nice day I'll see you tonight    8.0
25                                         Oh Ok! Ttyl     8.0
26                                             Alright     8.0
27           Thank you for tonight! I had a great time     8.0
28                                                         8.0
29                               Okay have a good night    8.0
...                                                 ...    ...
3504                                                  è   15.0
3505                                             Igual    15.0
3506                              Voy a doblar la ropa    15.0
3507                                                Sii   15.0
3508  Hmmmm dejame ir pAra jabonarte la espalda ;)y ...   15.0
3509       K Bn y Estas en [PLACE, 2] oh en [PLACE, 5]    15.0
3510                                              Hello   15.0
3511                                       Gracias amOr   15.0
3512                                   el tullo mamo yo   15.0
3513                                          Ofcoursee   15.0
3514                                               Hey    15.0
3515                                             Wasusp   15.0
3516                      Y Ahora Estas en la Casa Ya ?   15.0
3517          Good morning Babyque tengas un Lindo dia    15.0
3518                             Mandame Una pic tulla    15.0
3519                                   Como amaneciste    15.0
3520                                    No lo lei Amor    15.0
3521                                 Pero Tu MeGustaaa    15.0
3522                                                      15.0
3523                                Tu me gustas mucho    15.0
3524                  En que Parte de [PLACE, 9] vives    15.0
3525                                          Para que    15.0
3526                                   Cuando me llames   15.0
3527                            No te llego el mensaje    15.0
3528                                       Donde tuèTa    15.0
3529                                               Olax   15.0
3530                                sent me a pic of u    15.0
3531                                            [IMAGE]   15.0
3532                                                Ok    15.0
3533                                                 Ok   15.0

[3534 rows x 2 columns]

# Define train&test data

In [74]:
y=Data['Label'].values
X=Data['text'].values

In [75]:
from sklearn import cross_validation
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.3, random_state=0)

/Users/zhangshengjun/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# Vectorize data

We use count vectorizer and tfidf vectorizer

In [83]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [77]:
# unigram_count = CountVectorizer(encoding='latin-1', min_df=5, stop_words=None)

In [84]:
unigram_tfidf = TfidfVectorizer(encoding='latin-1', min_df=5, use_idf=True, smooth_idf=True, norm=u'l2')

In [85]:
X_train_vec = unigram_tfidf.fit_transform(X_train)

# Naive Bayes Classification

In [86]:
from sklearn.naive_bayes import MultinomialNB
nb_clf= MultinomialNB()
nb_clf.fit(X_train_vec,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [87]:
X_test_vec = unigram_tfidf.transform(X_test)

In [88]:
nb_clf.score(X_test_vec,y_test)

0.49198868991517436

In [89]:
from sklearn.metrics import confusion_matrix
y_pred = nb_clf.fit(X_train_vec, y_train).predict(X_test_vec)
cm = confusion_matrix(y_test, y_pred)
print (cm)

[[ 16  12  89   5   2]
 [  2  56 132   4  10]
 [ 12  34 420   8   6]
 [ 12  10 101   6   7]
 [  1  18  71   3  24]]


In [93]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred, average=None)

array([ 0.37209302,  0.43076923,  0.51660517,  0.23076923,  0.48979592])

# LR Classification

In [94]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [95]:
lr.fit(X_train_vec,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [96]:
lr.score(X_test_vec,y_test)

0.49858623939679547

In [97]:
from sklearn.metrics import confusion_matrix
y_pred = lr.fit(X_train_vec, y_train).predict(X_test_vec)
cm=confusion_matrix(y_test, y_pred)
print (cm)

[[ 13  14  89   7   1]
 [  3  57 126   4  14]
 [ 10  37 409  10  14]
 [  9  16  92  11   8]
 [  1  18  54   5  39]]
